title: NE30104
author:
    name: liyangxia
description: > # this means to ignore newlines until "show_excerpts:"
    The more you know, the more you don't know.

show_excerpts: false # set to true to show excerpts on the homepage
timezone: Asia/Shanghai

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
    date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

# Markdown
markdown:    kramdown
highlighter: rouge
rdiscount:
    extensions: []

redcarpet:
    extensions: []

kramdown:
    input:          GFM
    auto_ids:       true
    footnote_nr:    1
    entity_output:  as_char
    toc_levels:     1..6
    smart_quotes:   lsquo,rsquo,ldquo,rdquo
    enable_coderay: false
    
    coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
